export {default as Home} from "./Home"
export {default as Inicio} from "./Inicio"
export {default as Cadastro} from "./Cadastro"
export {default as Login} from "./Login"
export {default as Perfil} from "./Perfil"
export {default as Previa} from "./Previa"
export {default as Foruns} from "./Foruns"
export {default as Cursos_Disp} from "./Cursos_Disp"
export {default as Cursos_Adq} from "./Cursos_Adq"

export {default as StoreCurso} from "./Adm/Curso/Store"
export {default as AdmCurso} from "./Adm/Curso"